name: CI
on:
  - push
  - pull_request

# A workflow is made up of one or more jobs
jobs:

  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          # Recent LTS
          - node: 20.x
          # Provided by Debian 12 Bookworm LTS
          - node: 18.x
          # Provided by Debian 11 Bullseye LTS
          - node: 12.x
          # Provided by Debian 10 Buster LTS
          - node: 10.x

    name: "Test Node.js ${{ matrix.node }} "
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - run: npm install

      - run: npm test
