name: CI
on:
  - push
  - pull_request

# A workflow is made up of one or more jobs
jobs:

  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          # Recent LTS
          - node: 16.x
          # LTS for Debian Bullseye (used on some jq servers)
          - node: 12.x
          # LTS for Debian Buster (used on some jq servers)
          - node: 10.x

    name: "Test Node.js ${{ matrix.node }} "
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - run: npm install

      - run: npm test
